# Generated by Django 5.1.4 on 2025-02-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("shopName", models.CharField(max_length=200)),
                ("shopAddress", models.TextField()),
                ("shopFullAddress", models.TextField(blank=True, null=True)),
                ("pincode", models.CharField(max_length=6)),
                ("mobile", models.CharField(max_length=10, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("businessType", models.CharField(max_length=200)),
                ("shopDescription", models.TextField()),
                ("panNumber", models.CharField(max_length=10)),
                ("gstNumber", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
